#!/bin/bash

# Archive the input file to a predetermined location

# Check we have exactly 1 argument
if [ $# -ne 1 ]
then
  echo "Usage: $0 FILE"
  exit 1 # Quit the script, indicate an error to the shell
fi

# The archive location
archive=/home/pi/archives

# Make the destination if it does not already exist
mkdir -p $archive

# Copy the input file
cp -r $1 $archive